// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZekyVoxDwdP9ZQOr5T7okUO-SBtRLR-Q',
    appId: '1:179337004221:web:92262a7362251eeebfa3d4',
    messagingSenderId: '179337004221',
    projectId: 'monumental-habits-f1eec',
    authDomain: 'monumental-habits-f1eec.firebaseapp.com',
    storageBucket: 'monumental-habits-f1eec.firebasestorage.app',
    measurementId: 'G-WR99XKN8R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGPxJ0C5dDzSbQlqcql0xcltNqiqGgBsg',
    appId: '1:179337004221:android:1dd9f6500124a3f8bfa3d4',
    messagingSenderId: '179337004221',
    projectId: 'monumental-habits-f1eec',
    storageBucket: 'monumental-habits-f1eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRRARFPLApLy9kX32UPmFazw4_ilMo70',
    appId: '1:179337004221:ios:704bc8b38f86a764bfa3d4',
    messagingSenderId: '179337004221',
    projectId: 'monumental-habits-f1eec',
    storageBucket: 'monumental-habits-f1eec.firebasestorage.app',
    iosBundleId: 'com.example.monumentalHabits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWRRARFPLApLy9kX32UPmFazw4_ilMo70',
    appId: '1:179337004221:ios:704bc8b38f86a764bfa3d4',
    messagingSenderId: '179337004221',
    projectId: 'monumental-habits-f1eec',
    storageBucket: 'monumental-habits-f1eec.firebasestorage.app',
    iosBundleId: 'com.example.monumentalHabits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZekyVoxDwdP9ZQOr5T7okUO-SBtRLR-Q',
    appId: '1:179337004221:web:b4ccd94dba8d6b5dbfa3d4',
    messagingSenderId: '179337004221',
    projectId: 'monumental-habits-f1eec',
    authDomain: 'monumental-habits-f1eec.firebaseapp.com',
    storageBucket: 'monumental-habits-f1eec.firebasestorage.app',
    measurementId: 'G-1PPXZFCPC9',
  );
}
